development:
  adapter: postgresql
  database: friends_on_parade_development
  encoding: utf8
  min_messages: warning
test:
  adapter: postgresql
  database: friends_on_parade_test
  encoding: utf8
  min_messages: warning
